### ISSUE TITLE
Working on localhost, but not on production

### ISSUE THREAD

**Issue by ste7** [nuxt-community/laravel-echo-module#29]
Hello,

Everything is working perfectly fine on local machine, but on remove server `$echo` is undefined `TypeError: Cannot read property 'private' of undefined`

nuxt: 2.0.0,
laravel-echo: 1.1.0

```
modules: [
    '@nuxtjs/laravel-echo',
],
echo: {
    broadcaster: 'pusher',
    authModule: true,
    connectOnLogin: true,
    disconnectOnLogout: true,
    authEndpoint: process.env.API_BASE_URL + '/api/broadcasting/auth',
    key: process.env.PUSHER_APP_KEY,
    cluster: process.env.PUSHER_APP_CLUSTER,
    forceTLS: true,
    encrypted: process.env.PUSHER_APP_ENCRYPTED
}
```

```
mounted() {
    console.log(this.$echo) // TypeError: Cannot read property 'private' of undefined
}
```

 Dones anyone have idea how to solve this?

Thanks

**Comment by VinceSanityyy** [comment]
how did you manage to work it on localhost? Because mine is not working even if i send custom events in laravel websockets

**Comment by ricardogobbosouza** [comment]
Duplicated #41
